version: '3.8'

services:
  psyfind:
    build: .
    container_name: psyfind-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-5000}:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    env_file:
      - .env.production
    volumes:
      - ./psyfind.db:/app/psyfind.db
      - ./logs:/app/logs
    networks:
      - psyfind-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: psyfind-nginx
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - psyfind
    networks:
      - psyfind-network

  # Optional: Add Redis for session storage and caching
  redis:
    image: redis:alpine
    container_name: psyfind-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - psyfind-network

networks:
  psyfind-network:
    driver: bridge

volumes:
  redis-data:
