#!/bin/bash
# Fix script for PsyFind systemd service environment file issue

set -e

APP_DIR="/opt/psyfind"
SERVICE_NAME="psyfind"

echo "🔧 PsyFind Service Fix"
echo "======================"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    echo "❌ This script must be run as root"
    echo "Usage: sudo ./fix-service.sh"
    exit 1
fi

# Check if service exists
if [ ! -f "/etc/systemd/system/${SERVICE_NAME}.service" ]; then
    echo "❌ Service file not found at /etc/systemd/system/${SERVICE_NAME}.service"
    exit 1
fi

echo "📋 Checking service configuration..."

# Check if environment file exists
if [ -f "$APP_DIR/.env.production" ]; then
    echo "✅ Environment file exists at $APP_DIR/.env.production"
else
    echo "⚠️  Environment file missing at $APP_DIR/.env.production"
    echo "📝 Creating environment file..."
    
    # Create the environment file with minimal required settings
    cat > "$APP_DIR/.env.production" << 'EOF'
# PsyFind Production Configuration
# Generated by fix-service.sh

# LLM Provider Selection
LLM_PROVIDER=auto

# Ollama Configuration
OLLAMA_URL=http://localhost:11434

# OpenAI Configuration (optional)
OPENAI_API_KEY=your_openai_api_key_here

# OpenRouter Configuration (optional)
OPENROUTER_API_KEY=your_openrouter_api_key_here

# Flask Configuration
FLASK_ENV=production
FLASK_DEBUG=False
FLASK_SECRET_KEY=change-this-in-production-use-random-string

# Admin Panel Configuration
ADMIN_PASSWORD=admin123
DOCTOR_PASSWORD=doctor123
PASSWORD_SALT=change-this-salt-in-production
EOF

    # Set proper ownership and permissions
    chown psyfind:psyfind "$APP_DIR/.env.production"
    chmod 600 "$APP_DIR/.env.production"
    
    echo "✅ Environment file created"
fi

# Check if app directory exists
if [ ! -d "$APP_DIR" ]; then
    echo "❌ Application directory not found at $APP_DIR"
    exit 1
fi

echo "🔍 Checking application files..."

# Check if app.py exists
if [ ! -f "$APP_DIR/app.py" ]; then
    echo "❌ app.py not found in $APP_DIR"
    echo "💡 Please run the deployment script first: sudo ./deploy.sh deploy"
    exit 1
fi

# Check if venv exists
if [ ! -d "$APP_DIR/venv" ]; then
    echo "❌ Python virtual environment not found at $APP_DIR/venv"
    echo "💡 Please run the deployment script first: sudo ./deploy.sh deploy"
    exit 1
fi

# Check service file for correct paths
echo "🔧 Checking service file..."

# Read current service file and check for EnvironmentFile line
if grep -q "^EnvironmentFile=" "/etc/systemd/system/${SERVICE_NAME}.service"; then
    echo "✅ Service file has EnvironmentFile directive"
    
    # Check if the path is correct
    ENV_FILE_PATH=$(grep "^EnvironmentFile=" "/etc/systemd/system/${SERVICE_NAME}.service" | cut -d= -f2)
    echo "   Current path: $ENV_FILE_PATH"
    
    if [ "$ENV_FILE_PATH" != "$APP_DIR/.env.production" ]; then
        echo "⚠️  Environment file path in service doesn't match expected path"
        echo "   Expected: $APP_DIR/.env.production"
        echo "   Found: $ENV_FILE_PATH"
    fi
else
    echo "⚠️  Service file missing EnvironmentFile directive"
    echo "   Adding EnvironmentFile to service..."
    
    # Add EnvironmentFile line after the WorkingDirectory line
    sed -i "/^WorkingDirectory=/a EnvironmentFile=$APP_DIR/.env.production" "/etc/systemd/system/${SERVICE_NAME}.service"
    
    echo "✅ EnvironmentFile directive added"
fi

# Reload systemd
echo "🔄 Reloading systemd..."
systemctl daemon-reload

# Check if service can start
echo "🚀 Testing service start..."
if systemctl start "$SERVICE_NAME"; then
    echo "✅ Service started successfully"
    
    # Check if service is running
    if systemctl is-active --quiet "$SERVICE_NAME"; then
        echo "✅ Service is running"
        systemctl status "$SERVICE_NAME" --no-pager
    else
        echo "⚠️  Service started but not active"
        echo "📋 Checking for errors..."
        journalctl -u "$SERVICE_NAME" -n 20 --no-pager
    fi
else
    echo "❌ Service failed to start"
    echo "📋 Recent logs:"
    journalctl -u "$SERVICE_NAME" -n 20 --no-pager
    
    echo ""
    echo "🔍 Additional diagnostic information:"
    echo "--------------------------------------"
    
    # Check file permissions
    echo "File permissions:"
    ls -la "$APP_DIR/.env.production" || echo "   File not found"
    
    # Check directory permissions
    echo "Directory permissions:"
    ls -la "$APP_DIR" | head -5
    
    # Check if user exists
    if id "psyfind" &>/dev/null; then
        echo "✅ User 'psyfind' exists"
    else
        echo "❌ User 'psyfind' does not exist"
    fi
    
    # Check gunicorn
    if [ -f "$APP_DIR/venv/bin/gunicorn" ]; then
        echo "✅ Gunicorn exists in venv"
    else
        echo "❌ Gunicorn not found in venv"
    fi
fi

echo ""
echo "📝 Service Commands:"
echo "   Start:   sudo systemctl start $SERVICE_NAME"
echo "   Stop:    sudo systemctl stop $SERVICE_NAME"
echo "   Status:  sudo systemctl status $SERVICE_NAME"
echo "   Logs:    sudo journalctl -u $SERVICE_NAME -f"
echo ""
echo "✅ Fix complete!"
